### PR TITLE
Oauth2 with GitHub

### PR DESCRIPTION
**Pull request by jhthorsen**
Integration with Github instead of Eventbrite.

### CODE REVIEW

**Comment by jberger** [comment]
It looks good to me, is this something I can test?

**Comment by jberger** [comment]
put it another way, do we have a registered application and keys/secrets?

**Comment by jhthorsen** [comment]
Yes and no.

We have an application: https://github.com/organizations/mojoconf/settings/applications

But you can't test with that, because of the nature of OAuth2: You need to have a valid redirect_uri to make it safe.

We could on the other hand register a new application, which has "Authorization callback URL" set to `http://localhost:3000/connect`.

**Comment by jhthorsen** [comment]
Yeah, that worked:
- Set up mct.development.conf with the credentials from the "mct-test-localhost" app
- Start: morbo script/mct --listen http://*:5000
- Go to http://localhost:5000/profile

Do not start the application with MCT_MOCK=1

**Comment by jhthorsen** [comment]
Btw: `MCT_MOCK=1 morbo ...` will enable you to test it with local mocked date, meaning it does not require integration with github.com

**Comment by jberger** [comment]
assuming actually functions I give it a :+1: for merge, @jhthorsen if you are confident then go ahead. I don't have time to actually test it currently, but this is necessary for other work, so do as you see fit.

**Comment by jhthorsen** [comment]
Thanks! I've tested it locally, so I'm pretty confident it works :smile_cat:

**Pull request merged**
