### PR TITLE
added call for paper text to submission form

### PR DESCRIPTION
**Pull request by jberger**
Note that the text is only shown for submission not editing.

Its a bit of a halfway house, I don't like that there is the "magic template name" but, oh well.

### CODE REVIEW

**Comment by jberger** [comment]
@rpcme ping

**Comment by jhthorsen** [comment]
I think @rpcme had input on where he wanted this. It's fine for me just to add text "where-ever" directly in master when it's ready.

**Comment by jhthorsen** [comment]
```
deploy development call_for_papers
```

This PR is currently live on http://test.mojoconf.com/2015. Scroll down to the "Speakers" section, and you will find an clickable "user-plus" icon. Let me know what you think.

**Comment by jhthorsen** [comment]
I think this is closed by having 38fe39d509904ed59d313896f114034577f28736 in master.

**Pull request closed without merging**
